# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: server.proto for package 'proto'

require 'grpc'
require 'server_pb'

module Proto
  module UserInfo
    # The UserInfo service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.UserInfo'

      rpc :GetUser, UserRequest, UserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
