# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("server.proto", :syntax => :proto3) do
    add_message "proto.UserRequest" do
      optional :id, :string, 1
    end
    add_message "proto.UserResponse" do
      optional :message, :string, 1
    end
  end
end

module Proto
  UserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UserRequest").msgclass
  UserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UserResponse").msgclass
end
